backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Shop Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Thumbnail", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Stripe Checkout Link", name: "stripe_url", widget: "string" }
